### ISSUE TITLE
unable to download resources

### ISSUE THREAD

**Issue by yulinchen99** [CogComp/CogCompTime#1]
"If you have trouble downloading them, you can try this back-up link (300MB) and unzip it into $HOME/.cogcomp-datastore"

I cannot download the file, the back-up link is currently disabled

**Comment by qiangning** [comment]
@ cyl628 
Please use this link instead: https://qiangning.info/misc/cogcomp-datestore.tar.gz

@HeglerTissot Please also update the README page using this new link.

The reason is that my illinois homepage has been disabled since I left.

**Comment by yulinchen99** [comment]
thx! Another problem, could you also upload Gurobi Optimizer 6.5.2 ? The version is outdated and no longer downloadable on the official website. 

@qiangning

**Comment by qiangning** [comment]
Hi I think we have put gurobi.jar in the lib/ folder of this repo. Thanks.

**Comment by yulinchen99** [comment]
Sorry my expression may have been ambiguous. I actually meant the Gurobi software that is instructed to be downloaded manually in README, here "Have Gurobi installed in your system and have the environment variables GUROBI_HOME and GRB_LICENSE_FILE setup in your path". I tried downloading version 8.1.0 but it is not compatible with the gurobi.jar in the lib/ folder of the repo.
Thank you so much!

@qiangning

**Comment by qiangning** [comment]
Hi @cyl628 , in the [Compile](https://github.com/CogComp/CogCompTime#compile) section of README, you will see that Gurobi 6.5.2 will be installed using the `./lib/gurobi.jar` file. This means you don't actually need to download Gurobi from the official website anymore. You can set up the environment vars first according to our instructions in this repo. If it doesnt' work, you may still need to look up the most recent tutorial on their website in terms of setting up the environment variables.

**Comment by qiangning** [comment]
I also did see Gurobi 8.1.0 still available there: 
![image](https://user-images.githubusercontent.com/1971109/109010449-c7341180-767d-11eb-8f01-1c2296162df7.png)

Note we explained in the README that we also tested using Gurobi 8.1.0 and it worked the same, so you can also try that out.

**Comment by yulinchen99** [comment]
thanks for your explanation! It works.
